In [7]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
X,y = load_digits(return_X_y=True)
print('X',X.shape)
print('y',y.shape)
print(np.unique(y,return_counts=True))

X (1797, 64)
y (1797,)
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180], dtype=int64))


In [5]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.33, random_state=0)

In [11]:
model = KNeighborsClassifier(n_neighbors=9)
model.fit(Xtrain,ytrain)
ypredict = model.predict(Xtest)
print('Accuracy',accuracy_score(ytest,ypredict))
print('Confusion matrix')
print(confusion_matrix(ytest,ypredict))

Accuracy 0.9747474747474747
Confusion matrix
[[49  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  1 60  0  0  0  0  1  0  0]
 [ 0  0  0 55  0  0  0  0  0  0]
 [ 0  0  0  0 49  0  0  1  0  0]
 [ 0  0  0  0  0 62  1  0  0  2]
 [ 0  0  0  0  0  0 67  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  5  0  2  0  0  0  1 59  0]
 [ 0  0  0  0  0  1  0  0  0 61]]


In [13]:
model = NearestCentroid()
model.fit(Xtrain,ytrain)
ypredict = model.predict(Xtest)
print('Accuracy',accuracy_score(ytest,ypredict))
print('Confusion matrix')
print(confusion_matrix(ytest,ypredict))

Accuracy 0.8888888888888888
Confusion matrix
[[49  0  0  0  0  0  0  0  0  0]
 [ 0 46  5  0  0  1  2  0  0  7]
 [ 1  2 53  3  0  0  0  2  0  1]
 [ 0  0  1 46  0  0  0  2  2  4]
 [ 0  1  0  0 46  0  0  3  0  0]
 [ 0  0  0  0  0 54  1  0  0 10]
 [ 0  1  0  0  0  0 66  0  0  0]
 [ 0  0  0  0  0  0  0 55  1  0]
 [ 0  5  0  1  0  1  0  1 55  4]
 [ 0  0  0  0  0  1  0  3  0 58]]


In [14]:
model = SVC()
model.fit(Xtrain,ytrain)
ypredict = model.predict(Xtest)
print('Accuracy',accuracy_score(ytest,ypredict))
print('Confusion matrix')
print(confusion_matrix(ytest,ypredict))

Accuracy 0.9882154882154882
Confusion matrix
[[49  0  0  0  0  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 62  0  0  0  0  0  0  0]
 [ 0  0  0 54  0  0  0  0  1  0]
 [ 0  0  0  0 50  0  0  0  0  0]
 [ 0  0  0  0  0 63  1  0  0  1]
 [ 0  0  0  0  0  0 67  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  3  0  0  0  0  0  0 64  0]
 [ 0  0  0  0  0  1  0  0  0 61]]
